import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";
import Image from "next/image";
import { Main } from "../components/Main";
import ReduxProvider from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Train Schedule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full p-10`}>
        <div className="flex flex-col h-full gap-10">
          <Image
            src="/images/mainImage.jpg"
            alt="Main BG"
            className="absolute inset-0 z-[-10] object-cover w-full h-full"
            width={1088}
            height={608}
          />
          <ReduxProvider>
            <Header />
            <Main>{children}</Main>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
